"""
Django settings for AuthLog project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more info on settings, see:
https://docs.djangoproject.com/en/5.2/topics/settings/
"""

from pathlib import Path

# This sets the base directory of your project so you can refer to files easily
BASE_DIR = Path(__file__).resolve().parent.parent

# SECURITY WARNING: keep the secret key secret in production!
SECRET_KEY = 'django-insecure-56es-13q3og*-2i9l=#wwnj%^-yex#g6vxo-)bk2j!)7q$37$$'

# Debug mode means you see detailed error messages, only use in development
DEBUG = True

# Hosts/domain names that this Django site can serve
ALLOWED_HOSTS = []

# Installed apps - these are all the apps Django will use in your project
INSTALLED_APPS = [
    'django.contrib.admin',        # Admin site
    'django.contrib.auth',         # User authentication system
    'django.contrib.contenttypes', # Content type framework
    'django.contrib.sessions',     # Session framework
    'django.contrib.messages',     # Message framework
    'django.contrib.staticfiles',  # Manage static files like CSS and JS
    'grabsomore',                  # Your custom app for auth
    'eCommerce',                  # Your custom app for eCommerce
]

# Middleware are layers that process requests/responses, like security and session management
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware', 
    'django.middleware.csrf.CsrfViewMiddleware', # Protects against CSRF attacks
    'django.contrib.auth.middleware.AuthenticationMiddleware', # Adds user info to requests
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware', # Prevents clickjacking attacks
]

# Root URL configuration points to the main urls.py
ROOT_URLCONF = 'AuthLog.urls'

# Templates settings to tell Django where your HTML files are and how to process them
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],  # You can add folders here if you keep templates outside apps
        'APP_DIRS': True, # Tells Django to look for templates inside each app’s 'templates' folder
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request', # Adds 'request' object to templates
                'django.contrib.auth.context_processors.auth', # Adds user info to templates
                'django.contrib.messages.context_processors.messages', # Add message framework to templates
            ],
        },
    },
]

# WSGI application: Entry point for WSGI-compatible web servers
WSGI_APPLICATION = 'AuthLog.wsgi.application'

# Database settings: Using MySQL here with your database credentials
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',  # Use MySQL database engine
        'NAME': 'ecommerce_db',                # Your database name
        'USER': 'root',                        # Your database user
        'PASSWORD': 'password',                # Your database password
        'HOST': 'localhost',                   # Database is hosted on your own machine
        'PORT': '',                           # Default MySQL port (3306)
    }
}

# Password validation helps make sure passwords are strong and safe
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',},
]

# Internationalization settings (language and timezone)
LANGUAGE_CODE = 'en-us'  # English (United States)
TIME_ZONE = 'UTC'        # Coordinated Universal Time
USE_I18N = True          # Enable internationalization
USE_TZ = True            # Use timezone-aware datetimes

# Static files (CSS, JavaScript, images) URL prefix
STATIC_URL = 'static/'

# Default primary key type for models
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Email settings to send emails (for example, password reset emails)
# You can switch to console backend for testing emails in your terminal instead of sending real emails
# EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"  # Use SMTP server to send real emails
EMAIL_FILE_PATH = "/emails/"                                   # Path to save emails if using file backend
EMAIL_HOST = 'smtp.gmail.com'                                 # Gmail SMTP server
EMAIL_PORT = 587                                              # SMTP port for TLS
EMAIL_USE_TLS = True                                          # Use TLS for security
EMAIL_HOST_USER = 'your_email@gmail.com'                 # Your email address used to send mails
EMAIL_HOST_PASSWORD = 'your_app_password'                   # Your email password or app password

