# Generated by hand: create Store and migrate existing products to stores
from django.db import migrations, models
import django.db.models.deletion


def create_stores_and_assign(apps, schema_editor):
    Product = apps.get_model('eCommerce', 'Product')
    Store = apps.get_model('eCommerce', 'Store')
    User = apps.get_model('auth', 'User')

    vendor_ids = Product.objects.exclude(vendor__isnull=True).values_list('vendor', flat=True).distinct()
    vendor_to_store = {}
    for vid in vendor_ids:
        try:
            user = User.objects.get(pk=vid)
        except User.DoesNotExist:
            continue
        store = Store.objects.create(owner_id=vid, name=f"{user.username}'s Store", description='')
        vendor_to_store[vid] = store.id

    # Assign products
    for p in Product.objects.all():
        if p.vendor_id and p.vendor_id in vendor_to_store:
            p.store_id = vendor_to_store[p.vendor_id]
            p.save()


def remove_created_stores(apps, schema_editor):
    Store = apps.get_model('eCommerce', 'Store')
    Store.objects.filter(name__endswith="'s Store").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('eCommerce', '0002_alter_product_options_product_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='auth.user')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='eCommerce.store'),
        ),
        migrations.RunPython(create_stores_and_assign, remove_created_stores),
    ]
