# Generated by Django 5.2.4 on 2026-08-13 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0002_publisher_editors_publisher_journalists'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role_approved',
            field=models.BooleanField(default=True),
        ),
    ]
