# Generated by Django 5.2.4 on 2026-08-17 01:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0003_customuser_role_approved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role_approved',
        ),
    ]
