# Generated by Django 5.2.4 on 2026-08-08 19:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='editors',
            field=models.ManyToManyField(blank=True, related_name='managed_publishers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='publisher',
            name='journalists',
            field=models.ManyToManyField(blank=True, related_name='publisher_journalists', to=settings.AUTH_USER_MODEL),
        ),
    ]
